BEGIN;

DROP TABLE IF EXISTS "review" , "book", "user", "ticket", "attraction", "category";


CREATE TABLE "category" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE "attraction" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL,
  "description" VARCHAR(255) NOT NULL,
  "image" VARCHAR(255) NOT NULL,
  "duration" TIME NOT NULL,
  "category_id" INT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  FOREIGN KEY ("category_id") REFERENCES "category" ("id") ON DELETE CASCADE
);

CREATE TABLE "ticket" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" INT NOT NULL,
  "name" VARCHAR(64) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE "user" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mail" VARCHAR(128) UNIQUE NOT NULL,
  "first_name" VARCHAR(64) NOT NULL,
  "last_name" VARCHAR(64) NOT NULL,
  "password" VARCHAR(128) ,
  "role" VARCHAR(64) NOT NULL DEFAULT 'user',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now()
);


CREATE TABLE "book" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reservation_number" VARCHAR(255),
  "visit_date" TIMESTAMP WITH TIME ZONE DEFAULT NOW() ,
  "quantity" INT NOT NULL,
  "ticket_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  FOREIGN KEY ("ticket_id") REFERENCES "ticket" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE "review" (
  "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "note" INT NOT NULL CHECK ("note" BETWEEN 1 AND 5), -- note sur 5
  "commentaire" TEXT,
  "user_id" INT NOT NULL,
  "attraction_id" INT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("attraction_id") REFERENCES "attraction" ("id") ON DELETE CASCADE,
  CONSTRAINT unique_user_attraction_review UNIQUE ("user_id", "attraction_id")
);


COMMIT;